name: aws-deploy

#on:
#  release:
#    types: [created]
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Version
        id: set-version
        # `::set-output name=XXX::VALUE`の形式でechoするとcontextとして使用できる
        run: |
          VERSION=`echo -n ${{ github.ref }} | sed -e "s@refs/tags/@@g"`
          echo ::set-output name=version::${VERSION}
          echo version: ${VERSION}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
          VERSION: ${{ step.set-version.output.version }}
        run: |
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION}

      - name: Render Amazon ECS task definition
        run: |
          echo comming soon...

      - name: Deploy to CloudWatch Rule
        run: |
          echo comming soon...
